livery: tiger_stripes
random_seed: 1
wheelbase: 2.7
front_tire_dia: 1.0
front_tire_width: 0.2
front_tire_depth: 0.2
rear_tire_dia: 1.6
rear_tire_width: 0.3
rear_tire_depth: 0.2
front_track_width: 1.0
rear_track_width: 1.6
turning_radius: 2.7
sensor_pod_length: 2.0
sensor_pod_width: 1.5
sensor_pod_height: 0.2
sensor_pod_height_above_ground: 2.3
tractor_body_length: 3.5
tractor_body_width: 1.5 
tractor_body_height: 1.0
tractor_body_ground_clearance: 0.3
tractor_body_front_axle: 0.3
wheel_well_clearance: 0.08
front_camera: true
rear_camera: false
left_camera: false
right_camera: false
camera_pitch: 10.0
camera_hfov: 90.0
camera_resolution: [1280, 720]
